name: Bash GH Skeleton

on: [pull_request]

jobs:
  bash-gh-skeleton:
    runs-on: ubuntu-latest
    name: Whatever this action does
    steps:
      - uses: Tanoka/test@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          another_input: Some value
