name: Bash Pull Request Merger

on: [pull_request]

jobs:
  bash-pr-merger:
    runs-on: ubuntu-latest
    name: Merge pull requests when there is only a composer.lock file
    steps:
      - uses: Tanoka/automerge-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
